# Header
Archives: /archives
rss: /atom.xml

# Content
# excerpt_link: Read More

# Miscellaneous
google_analytics: UA-1951739-9
# favicon: /favicon.png
# twitter:
# google_plus:
# fb_admins:
# fb_app_id:
