# Header
menu:
- name: About
  path: /about-me
  logo: user
- name: Archives
  path: /archives
  logo: archive
- name: Tags
  path: /tags
  logo: tags
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

pages:
- about
- wiki

wiki_dir: wiki
wiki_info:

# Sidebar
sidebar: bottom
home_widgets:
- tag
- search
- blogroll
act_widgets:
- search
- recent_posts
- blogroll
post_widgets:
- post_date
- nav
- post_tag

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:

links:
- name: Github
  url: https://github.com/adsanderson/
  logo: github
# - name: Google+
#   url: https://plus.google.com/
#   logo: google-plus

feed:
  type: atom
  path: atom.xml
  limit: 20

sitemap:
  path: sitemap.xml
